"""
Schema validator for ReportService outputs.

Ports the rule-based validator from `~/.openclaw/workspace/harness_design/mnc/`
into BDGO so every report generated by `BuyerProfileService` (and future
`ReportService` subclasses) can be checked against a YAML schema contract.

Public API:
    validate_markdown(text, mode="mnc") -> AuditResult
    audit_to_dict(audit, max_findings=100) -> dict

The findings dict is small enough to stash in `report_history.meta_json`
so it travels with every task and surfaces in the UI / queries.

Mode selection:
    "mnc"                 → MNC schema (Pfizer, Sanofi, Lilly tier)
    "commercial_biotech"  → Commercial Biotech buyer schema (Insmed tier)

Schema files live in ``api/services/quality/schemas/``. Adding a new schema
is: drop a YAML next to the existing ones and register its mode in
``_SCHEMA_BY_MODE``.
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

import yaml

_SCHEMAS_DIR = Path(__file__).parent / "schemas"

_SCHEMA_BY_MODE: dict[str, str] = {
    "mnc": "mnc_main.yaml",
    "commercial_biotech": "commercial_biotech_main.yaml",
}


# ────────────────────────────────────────────────
# Data model
# ────────────────────────────────────────────────
@dataclass
class Block:
    """A document block: heading / paragraph / table."""

    kind: str  # 'heading' | 'paragraph' | 'table'
    level: int = 0
    text: str = ""
    n_rows: int = 0
    n_cols: int = 0


@dataclass
class Finding:
    severity: str  # 'fail' | 'warn' | 'info'
    category: str
    section: str
    message: str
    evidence: str = ""


@dataclass
class AuditResult:
    findings: list[Finding] = field(default_factory=list)
    stats: dict[str, Any] = field(default_factory=dict)

    def add(self, severity: str, category: str, section: str, message: str, evidence: str = ""):
        self.findings.append(Finding(severity, category, section, message, evidence[:200]))

    @property
    def n_fail(self) -> int:
        return sum(1 for f in self.findings if f.severity == "fail")

    @property
    def n_warn(self) -> int:
        return sum(1 for f in self.findings if f.severity == "warn")

    @property
    def n_info(self) -> int:
        return sum(1 for f in self.findings if f.severity == "info")


# ────────────────────────────────────────────────
# Document parsing
# ────────────────────────────────────────────────
def load_md_text(text: str) -> list[Block]:
    """Parse markdown string into ordered Block list. # = heading; |…| rows = table."""
    blocks: list[Block] = []
    lines = text.splitlines()
    i = 0
    while i < len(lines):
        line = lines[i].rstrip()
        if not line.strip():
            i += 1
            continue
        m = re.match(r"^(#{1,6})\s+(.+)$", line)
        if m:
            blocks.append(Block(kind="heading", level=len(m.group(1)), text=m.group(2).strip()))
            i += 1
            continue
        if line.strip().startswith("|"):
            tbl_lines = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                tbl_lines.append(lines[i].strip())
                i += 1
            n_rows = sum(1 for line in tbl_lines if not re.match(r"^\|[\s\-:|]+\|$", line))
            n_cols = max((line.count("|") - 1 for line in tbl_lines), default=0)
            blocks.append(
                Block(
                    kind="table",
                    text=" | ".join(tbl_lines),
                    n_rows=n_rows,
                    n_cols=n_cols,
                )
            )
            continue
        para_lines = [line]
        j = i + 1
        while (
            j < len(lines)
            and lines[j].strip()
            and not lines[j].lstrip().startswith("#")
            and not lines[j].strip().startswith("|")
        ):
            para_lines.append(lines[j].rstrip())
            j += 1
        blocks.append(Block(kind="paragraph", text=" ".join(para_lines)))
        i = j
    return blocks


def full_text(blocks: list[Block]) -> str:
    return "\n".join(b.text for b in blocks)


def count_chars(text: str) -> int:
    """Char-level count, whitespace stripped (CJK = 1 char, latin word ≈ N chars)."""
    return len(re.sub(r"\s+", "", text))


# ────────────────────────────────────────────────
# Section splitting
# ────────────────────────────────────────────────
@dataclass
class Section:
    id: str
    name: str
    start_idx: int
    end_idx: int
    blocks: list[Block] = field(default_factory=list)

    @property
    def text(self) -> str:
        return "\n".join(b.text for b in self.blocks)

    @property
    def char_count(self) -> int:
        return count_chars(self.text)

    def contains_heading(self, patterns: list[str]) -> Block | None:
        for b in self.blocks:
            if b.kind == "heading":
                for p in patterns:
                    if re.search(p, b.text, re.IGNORECASE):
                        return b
        return None

    def has_text(self, patterns: list[str]) -> list[str]:
        return [p for p in patterns if re.search(p, self.text, re.IGNORECASE)]

    def tables(self) -> list[Block]:
        return [b for b in self.blocks if b.kind == "table"]


def split_sections(blocks: list[Block], schema: dict) -> dict[str, Section]:
    all_sec_defs: list[tuple[str, str, str, list[str]]] = []
    for sec_def in schema.get("sections", []):
        all_sec_defs.append(
            ("ch", sec_def["id"], sec_def["name"], sec_def.get("heading_patterns", []))
        )
    for app in schema.get("appendices", []):
        pat = rf"附录\s*{app['id']}|Appendix\s+{app['id']}"
        all_sec_defs.append(("app", f"appendix_{app['id']}", app["name"], [pat]))

    sec_starts: dict[str, int] = {}
    for _kind, sid, _name, patterns in all_sec_defs:
        for i, b in enumerate(blocks):
            if b.kind != "heading":
                continue
            for p in patterns:
                if re.search(p, b.text, re.IGNORECASE):
                    sec_starts[sid] = i
                    break
            else:
                continue
            break

    ordered = sorted(sec_starts.items(), key=lambda kv: kv[1])
    result: dict[str, Section] = {}
    for idx, (sid, start) in enumerate(ordered):
        end = ordered[idx + 1][1] if idx + 1 < len(ordered) else len(blocks)
        name = next((n for _, s, n, _ in all_sec_defs if s == sid), sid)
        result[sid] = Section(
            id=sid, name=name, start_idx=start, end_idx=end, blocks=blocks[start:end]
        )

    first_main_start = ordered[0][1] if ordered else len(blocks)
    result["_front_matter"] = Section(
        id="_front_matter",
        name="Front Matter",
        start_idx=0,
        end_idx=first_main_start,
        blocks=blocks[:first_main_start],
    )
    return result


# ────────────────────────────────────────────────
# Check rules
# ────────────────────────────────────────────────
def check_front_matter(
    blocks: list[Block], sections: dict[str, Section], schema: dict, r: AuditResult
):
    fm = schema.get("front_matter", {})
    fm_text = sections.get("_front_matter", Section("", "", 0, 0)).text
    full = full_text(blocks)

    cov = fm.get("cover", {})
    if cov.get("required"):
        for kw in cov.get("must_contain", []):
            if not re.search(kw, full, re.IGNORECASE):
                r.add("fail", "front_matter", "cover", f'封面缺少关键词 "{kw}"')

    toc = fm.get("toc", {})
    if toc.get("required"):
        hits = [kw for kw in toc.get("must_contain_one_of", []) if re.search(kw, full)]
        if not hits:
            r.add("warn", "front_matter", "toc", '未检测到"目录"/Contents 标记')

    rg = fm.get("report_guide", {})
    if rg.get("required"):
        missing = [kw for kw in rg.get("must_contain_all", []) if not re.search(kw, full)]
        if missing:
            r.add(
                "fail",
                "front_matter",
                "report_guide",
                f"报告导引应回答的问题缺失: {missing}",
            )
        missing_groups = []
        for g_idx, group in enumerate(rg.get("must_contain_groups", [])):
            if not any(kw in full for kw in group):
                missing_groups.append({"group_idx": g_idx, "any_of": group})
        if missing_groups:
            r.add(
                "fail",
                "front_matter",
                "report_guide",
                f"报告导引应至少命中每组关键词一个，缺失组: {missing_groups}",
            )

    es = fm.get("exec_summary", {})
    if es.get("required"):
        labels = re.findall(es.get("label_format", ""), full)
        if len(labels) < es.get("min_labels", 5):
            r.add(
                "fail",
                "front_matter",
                "exec_summary",
                f'"核心发现 N" 标签数={len(labels)}，要求 >={es.get("min_labels", 5)}',
            )
        r.stats["front_matter_chars"] = count_chars(fm_text)

    fc = fm.get("firepower_card", {})
    if fc.get("required"):
        missing = [
            kw for kw in fc.get("must_contain_all", []) if not re.search(kw, full, re.IGNORECASE)
        ]
        if missing:
            r.add(
                "fail",
                "front_matter",
                "firepower_card",
                f"买方火力卡必须含以下字段，缺失: {missing}",
            )

    qh = fm.get("quick_hit_page", {})
    if qh.get("required"):
        qh_signals = [
            "Quick-Hit",
            "quick hit",
            "速读",
            "资产匹配清单",
            "3 分钟",
            "shopping list",
            "接触点",
            "first contact",
        ]
        sig_hits = [s for s in qh_signals if re.search(re.escape(s), full, re.IGNORECASE)]
        if not sig_hits:
            r.add(
                "fail",
                "front_matter",
                "quick_hit_page",
                f"Quick-Hit 页（BD 3 分钟速读页）缺失；未检测到任何信号词 {qh_signals}",
            )
        else:
            r.add(
                "info",
                "front_matter",
                "quick_hit_page",
                f"检测到 Quick-Hit 候选信号: {sig_hits[:3]}",
            )
            for blk in qh.get("required_blocks", []):
                block_signals = {
                    "asset_shopping_list": ["匹配清单", "shopping list", "watchlist", "在看的"],
                    "top3_directions_preview": ["Top 3", "Top3", "三个方向", "Top 3 方向"],
                    "top_directions_preview": [
                        "Top 2",
                        "Top2",
                        "两个方向",
                        "Top 3",
                        "Top3",
                        "三个方向",
                        "方向预览",
                        "Top 方向",
                        "Top directions",
                    ],
                    "first_contact_point": ["接触人", "接触点", "contact", "第一个敲门"],
                    "recommended_deal_structure_summary": ["建议结构", "推荐结构", "交易结构建议"],
                }
                expected = block_signals.get(blk, [blk])
                if not any(re.search(re.escape(k), full, re.IGNORECASE) for k in expected):
                    r.add(
                        "fail",
                        "front_matter",
                        f"quick_hit_page/{blk}",
                        f'Quick-Hit 页应含"{blk}"（关键词 {expected} 均未命中）',
                    )
            shopping_rules = qh.get("asset_shopping_list_rules", {})
            min_items = shopping_rules.get("min_items", 0)
            if min_items > 0:
                date_pat_hits = len(re.findall(r"20\d{2}-\d{2}-\d{2}", full))
                r.stats["shopping_list_date_hits"] = date_pat_hits


def check_sections(sections: dict[str, Section], schema: dict, r: AuditResult):
    for sec_def in schema.get("sections", []):
        sid = sec_def["id"]
        if sid not in sections:
            if sec_def.get("required", True):
                r.add(
                    "fail",
                    "section_missing",
                    sid,
                    f'章节"{sec_def["name"]}"未检测到（期望 heading: {sec_def.get("heading_patterns")}）',
                )
            continue
        sec = sections[sid]
        for sub in sec_def.get("subsections", []):
            sub_id = sub["id"]
            sub_name = sub["name"]
            id_prefix_pat = rf"^\s*{re.escape(sub_id)}[\s\.。:：]"
            hard_hit = False
            for b in sec.blocks:
                if re.match(id_prefix_pat, b.text):
                    hard_hit = True
                    break
            if not hard_hit:
                hard_hit = bool(sec.contains_heading([re.escape(sub_name)]))

            if not hard_hit:
                tokens = re.findall(r"[一-龥A-Za-z0-9]{2,}", sub_name)
                hit_tokens = sum(1 for t in tokens if t in sec.text)
                if hit_tokens >= max(1, len(tokens) // 2):
                    r.add(
                        "warn",
                        "subsection_soft",
                        f"{sid}.{sub_id}",
                        f'子章节"{sub_name}"未见"{sub_id}"前缀 heading，但正文出现 {hit_tokens}/{len(tokens)} 个关键 token',
                    )
                else:
                    if sub.get("required", False):
                        r.add(
                            "fail",
                            "subsection_missing",
                            f"{sid}.{sub_id}",
                            f'子章节"{sub_id} {sub_name}"缺失（无"{sub_id}"前缀 heading，且正文关键 token 命中 {hit_tokens}/{len(tokens)}）',
                        )
                    elif sub.get("nice_to_have"):
                        r.add(
                            "warn",
                            "subsection_optional",
                            f"{sid}.{sub_id}",
                            f'nice_to_have 子章节"{sub_id} {sub_name}"缺失（允许 "insufficient public data" 说明）',
                        )

            for kw in sub.get("must_contain_all", []):
                if not re.search(kw, sec.text, re.IGNORECASE):
                    r.add(
                        "fail",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f'子章节应含关键词 "{kw}"，未检测到',
                    )
            if sub.get("must_contain_one_of"):
                if not any(
                    re.search(k, sec.text, re.IGNORECASE) for k in sub["must_contain_one_of"]
                ):
                    r.add(
                        "fail",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f"子章节应至少含以下之一: {sub['must_contain_one_of']}",
                    )
            if sub.get("min_quotes"):
                quotes = re.findall(r'["“”][^"“”]{10,}["“”]', sec.text)
                if len(quotes) < sub["min_quotes"]:
                    r.add(
                        "fail",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f"应含 ≥{sub['min_quotes']} 个直接引述，检测到 {len(quotes)}",
                    )
            if sub.get("min_deep_dives"):
                cnt = len(
                    re.findall(r"案例[1-9一二三四五]|深度复盘|Deep Dive", sec.text, re.IGNORECASE)
                )
                if cnt < sub["min_deep_dives"]:
                    r.add(
                        "warn",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f"深度复盘案例数={cnt}，要求 >={sub['min_deep_dives']}",
                    )
            if sub.get("min_failures"):
                cnt = len(
                    re.findall(r"失败|terminated|miss endpoint|未达|撤市", sec.text, re.IGNORECASE)
                )
                if cnt < sub["min_failures"]:
                    r.add(
                        "warn",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f"失败案例关键词出现 {cnt} 次，要求 >={sub['min_failures']}",
                    )
            if sub.get("min_peers"):
                if not sec.tables():
                    r.add(
                        "warn",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f"未检测到同业对标表格（要求 ≥{sub['min_peers']} 家对标）",
                    )
            if sub.get("min_directions"):
                dir_patterns = [
                    r"方向\s*\d",
                    r"方向\s*[一二三四五六七八九十]",
                    r"Direction\s*\d",
                    r"Top\s*\d",
                    r"第[一二三四五六七八九十]\s*(?:个)?方向",
                ]
                hits = sum(len(re.findall(p, sec.text, re.IGNORECASE)) for p in dir_patterns)
                if hits < sub["min_directions"]:
                    r.add(
                        "fail",
                        "subsection_content",
                        f"{sid}.{sub_id}",
                        f"Top方向数={hits}，要求 >={sub['min_directions']}",
                    )


def check_ch3_iterative(sections: dict[str, Section], schema: dict, r: AuditResult):
    """ch3 repeats per TA — special handling."""
    ch3_def = next((s for s in schema["sections"] if s["id"] == "ch3"), None)
    if not ch3_def or "ch3" not in sections:
        return
    ch3 = sections["ch3"]
    min_items = ch3_def.get("min_items", 3)

    ta_ids: set[str] = set()
    for b in ch3.blocks:
        m = re.match(r"^\s*3\.(\d+)\b", b.text)
        if m:
            ta_ids.add(m.group(1))
    ta_count = len(ta_ids)
    if ta_count == 0:
        ta_keywords = [
            "肿瘤",
            "代谢",
            "心血管",
            "免疫",
            "疫苗",
            "罕见病",
            "神经",
            "血液",
            "眼科",
            "皮肤",
        ]
        ta_count = sum(1 for kw in ta_keywords if kw in ch3.text)

    r.stats["ch3_ta_count"] = ta_count
    if ta_count < min_items:
        r.add("fail", "ch3_iterative", "ch3", f"第3章TA数={ta_count}，要求 >={min_items}")

    tables_in_ch3 = len(ch3.tables())
    if tables_in_ch3 < ta_count:
        r.add(
            "warn",
            "ch3_iterative",
            "ch3",
            f"第3章表格数={tables_in_ch3}，TA数={ta_count}（每个TA应至少1张对标表）",
        )

    ch3_chars = ch3.char_count
    r.stats["ch3_chars"] = ch3_chars
    target = ch3_def.get("target_words", 15000)
    if ch3_chars < target * 0.5:
        r.add(
            "warn",
            "ch3_iterative",
            "ch3",
            f"第3章字数={ch3_chars}，目标 ~{target}（不足目标50%）",
        )


def check_appendices(sections: dict[str, Section], schema: dict, r: AuditResult):
    for app in schema.get("appendices", []):
        sid = f"appendix_{app['id']}"
        if sid not in sections:
            if app.get("required"):
                r.add(
                    "fail",
                    "appendix_missing",
                    sid,
                    f'附录 {app["id"]} "{app["name"]}" 未检测到',
                )


def check_banned_phrases(full: str, schema: dict, r: AuditResult):
    for rule in schema.get("quality_rules", {}).get("banned_patterns", []):
        pattern = rule["pattern"]
        matches = re.findall(pattern, full)
        if matches:
            severity = {"high": "fail", "medium": "warn", "low": "info"}[
                rule.get("severity", "medium")
            ]
            r.add(
                severity,
                "banned_phrase",
                f"writing/{rule.get('category', 'unknown')}",
                f'命中禁用词 "{pattern}" × {len(matches)}',
                evidence=", ".join(matches[:3]),
            )
    for pattern in schema.get("quality_rules", {}).get("banned_chars", []):
        if pattern == "emoji_range":
            emoji_re = re.compile(r"[\U0001F300-\U0001FAFF☀-➿]")
            emojis = emoji_re.findall(full)
            if emojis:
                r.add(
                    "warn",
                    "banned_chars",
                    "writing/emoji",
                    f"检测到 emoji {len(emojis)} 个",
                    evidence="".join(emojis[:5]),
                )
        else:
            matches = re.findall(pattern, full)
            if matches:
                r.add(
                    "warn",
                    "banned_chars",
                    "writing/decoration",
                    f'命中装饰符 "{pattern}" × {len(matches)}',
                )


def check_citations(full: str, schema: dict, r: AuditResult):
    rules = schema.get("citation_rules", {})
    used = [int(m.group(1)) for m in re.finditer(r"\[(\d+)\]", full)]
    used_set = set(used)
    ref_header_pat = rules.get("references_section", "参考来源")
    has_ref_section = bool(re.search(ref_header_pat, full))
    if not has_ref_section:
        r.add("fail", "citation", "references", '未检测到"参考来源"/References 章节')
        return

    m = re.search(ref_header_pat, full)
    refs_block = full[m.end() :] if m else ""
    declared = {int(mm.group(1)) for mm in re.finditer(r"\[(\d+)\]", refs_block)}

    r.stats["citations_used"] = sorted(used_set)
    r.stats["citations_declared"] = sorted(declared)

    orphan_used = used_set - declared
    if orphan_used:
        r.add(
            "fail",
            "citation",
            "references",
            f"正文引用 [N] 未在参考来源列表中声明: {sorted(orphan_used)}",
        )

    unused = declared - used_set
    if unused and rules.get("require_all_used"):
        r.add(
            "warn",
            "citation",
            "references",
            f"参考来源声明了但正文未引用: {sorted(unused)}",
        )

    if declared and rules.get("require_sequential"):
        expected = set(range(1, max(declared) + 1))
        gaps = expected - declared
        if gaps:
            r.add(
                "warn",
                "citation",
                "references",
                f"参考来源编号不连续，缺: {sorted(gaps)}",
            )


def check_total_words(full: str, schema: dict, r: AuditResult):
    tgt = schema.get("target_total_words", {})
    chars = count_chars(full)
    r.stats["total_chars"] = chars
    lo = tgt.get("min", 0)
    hi = tgt.get("max", 10**9)
    if chars < lo:
        r.add("fail", "total_length", "global", f"全文字数={chars}，目标 >={lo}")
    elif chars > hi:
        r.add("warn", "total_length", "global", f"全文字数={chars}，超出目标 <={hi}")


def check_cross_refs(sections: dict[str, Section], _schema: dict, r: AuditResult):
    ch3 = sections.get("ch3")
    ch8 = sections.get("ch8")
    if not ch3 or not ch8:
        return
    ch8_dir_words = re.findall(r"方向[1-9一二三四五]\s*[：:]\s*([^\n，。；]{2,20})", ch8.text)
    for w in ch8_dir_words[:5]:
        if w.strip() and w.strip() not in ch3.text:
            r.add(
                "warn",
                "cross_ref",
                "ch8→ch3",
                f'第8章Top方向"{w.strip()}"在第3章文本中未找到对应讨论',
            )


# ────────────────────────────────────────────────
# Public API
# ────────────────────────────────────────────────
def _resolve_schema(mode: str) -> Path:
    if mode not in _SCHEMA_BY_MODE:
        raise ValueError(f"Unknown schema mode '{mode}'. Known modes: {list(_SCHEMA_BY_MODE)}")
    p = _SCHEMAS_DIR / _SCHEMA_BY_MODE[mode]
    if not p.exists():
        raise FileNotFoundError(f"Schema file missing: {p}")
    return p


def validate_markdown(text: str, mode: str = "mnc") -> AuditResult:
    """Validate a markdown report against the schema for ``mode``.

    Args:
        text: Full markdown body of the report.
        mode: Schema selector. ``"mnc"`` for top-tier MNC buyer profiles,
            ``"commercial_biotech"`` for commercial biotech buyers.

    Returns:
        AuditResult with findings + stats. Doesn't raise on schema FAILs.
        Caller decides what to do with ``audit.n_fail``.
    """
    schema_path = _resolve_schema(mode)
    schema = yaml.safe_load(schema_path.read_text(encoding="utf-8"))
    blocks = load_md_text(text)

    r = AuditResult()
    r.stats["mode"] = mode
    r.stats["schema"] = schema_path.name
    r.stats["n_blocks"] = len(blocks)
    r.stats["n_headings"] = sum(1 for b in blocks if b.kind == "heading")
    r.stats["n_paragraphs"] = sum(1 for b in blocks if b.kind == "paragraph")
    r.stats["n_tables"] = sum(1 for b in blocks if b.kind == "table")

    sections = split_sections(blocks, schema)
    r.stats["detected_sections"] = sorted(sections.keys())

    full = full_text(blocks)

    check_front_matter(blocks, sections, schema, r)
    check_sections(sections, schema, r)
    check_ch3_iterative(sections, schema, r)
    check_appendices(sections, schema, r)
    check_banned_phrases(full, schema, r)
    check_citations(full, schema, r)
    check_total_words(full, schema, r)
    check_cross_refs(sections, schema, r)
    # Note: companion_data_pack check from harness is omitted here. BDGO
    # supports xlsx output (rnpv_valuation already uses it), but
    # BuyerProfileService v0 emits md+docx only — the v0.2.1 companion
    # xlsx is a separate follow-up. Re-enable this check when buyer_profile
    # starts emitting the data pack.

    return r


def audit_to_dict(audit: AuditResult, max_findings: int = 100) -> dict:
    """Serialise AuditResult into a JSON-safe dict for ``meta_json`` storage.

    ``max_findings`` truncates the list to keep ``meta_json`` rows bounded.
    Stats are always kept in full (small).
    """
    findings = audit.findings[:max_findings]
    truncated = max(0, len(audit.findings) - max_findings)
    return {
        "n_fail": audit.n_fail,
        "n_warn": audit.n_warn,
        "n_info": audit.n_info,
        "stats": audit.stats,
        "findings": [
            {
                "severity": f.severity,
                "category": f.category,
                "section": f.section,
                "message": f.message,
                "evidence": f.evidence,
            }
            for f in findings
        ],
        "findings_truncated": truncated,
    }
